#!/usr/bin/env bash
# Generated by zero_touch — do not edit by hand.
# Validates a commit message against the Conventional Commits specification.

set -euo pipefail

MSG_FILE="${1:?usage: validate-commit.sh <commit-msg-file>}"
SUBJECT=$(head -n 1 "$MSG_FILE")

# Ignore machine-generated commits that git creates for merges and reverts.
case "$SUBJECT" in
  "Merge "*|"Revert "*|"fixup!"*|"squash!"*) exit 0 ;;
esac

TYPES="feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert"
PATTERN="^(${TYPES})(\([a-z0-9._/-]+\))?!?: .+"

if ! printf '%s' "$SUBJECT" | grep -qE "$PATTERN"; then
  echo "❌ Invalid commit message:"
  echo "     $SUBJECT"
  echo ""
  echo "   Expected: <type>[optional scope][!]: <description>"
  echo "   Types:    ${TYPES//|/, }"
  echo "   Examples: feat: add login screen"
  echo "             fix(auth): handle expired tokens"
  echo "             refactor!: drop legacy API"
  exit 1
fi

if [ "${#SUBJECT}" -gt 100 ]; then
  echo "❌ Commit subject exceeds 100 characters (${#SUBJECT})."
  exit 1
fi
