#!/usr/bin/env bash
# Generated by zero_touch — do not edit by hand.
# Enforces the minimum coverage threshold for the configured project type.

set -euo pipefail

PROJECT_TYPE="${PROJECT_TYPE:?PROJECT_TYPE must be set}"
MIN_COVERAGE="${MIN_COVERAGE:-0}"

echo "Checking coverage for $PROJECT_TYPE (threshold: ${MIN_COVERAGE}%)"

# Coverage is computed to two decimal places. Integer arithmetic previously
# floored the score, making 79.9% indistinguishable from 79.0% at the gate.
percent() {
  awk -v c="$1" -v t="$2" 'BEGIN { if (t == 0) { print "0.00" } else { printf "%.2f", (100 * c) / t } }'
}

case "$PROJECT_TYPE" in
  flutter)
    LCOV="coverage/lcov.info"
    if [ ! -f "$LCOV" ]; then
      echo "Coverage file not found: $LCOV" >&2
      exit 1
    fi

    # Generated sources are excluded so the score reflects hand-written code.
    FILTERED="$(mktemp)"
    awk '
      /^SF:/ {
        skip = ($0 ~ /\.g\.dart$/ || $0 ~ /\.freezed\.dart$/ ||
                $0 ~ /\.pb\.dart$/ || $0 ~ /generated_plugin_registrant/ ||
                $0 ~ /\.mocks\.dart$/)
      }
      !skip { print }
    ' "$LCOV" > "$FILTERED"

    TOTAL=$(awk -F: '/^LF:/ {sum += $2} END {print sum + 0}' "$FILTERED")
    COVERED=$(awk -F: '/^LH:/ {sum += $2} END {print sum + 0}' "$FILTERED")
    rm -f "$FILTERED"
    ;;

  android)
    FILE=$(find build app/build -name "jacocoTestReport.xml" -type f 2>/dev/null | head -n 1 || true)
    if [ -z "$FILE" ]; then
      echo "Jacoco report not found under build/ or app/build/" >&2
      exit 1
    fi
    echo "Using report: $FILE"
    COVERED=$(grep -o 'covered="[0-9]*"' "$FILE" | grep -o '[0-9]*' | awk '{sum += $1} END {print sum + 0}')
    MISSED=$(grep -o 'missed="[0-9]*"' "$FILE" | grep -o '[0-9]*' | awk '{sum += $1} END {print sum + 0}')
    TOTAL=$((COVERED + MISSED))
    ;;

  ios)
    XCRESULT=$(find fastlane/test_output build/reports -name "*.xcresult" -maxdepth 3 2>/dev/null | head -n 1 || true)
    if [ -z "$XCRESULT" ]; then
      echo "No .xcresult found under fastlane/test_output or build/reports" >&2
      exit 1
    fi
    echo "Using result bundle: $XCRESULT"
    SCORE=$(xcrun xccov view --report "$XCRESULT" | awk '/Line Coverage/ {gsub(/[()%]/, "", $3); print $3; exit}')
    TOTAL=1
    ;;

  *)
    echo "Unsupported project type: $PROJECT_TYPE" >&2
    exit 1
    ;;
esac

if [ "$PROJECT_TYPE" != "ios" ]; then
  # A zero total means no instrumented lines were found at all, which is a
  # broken test run rather than 0% coverage — and previously divided by zero.
  if [ "$TOTAL" -eq 0 ]; then
    echo "No instrumented lines found — coverage data is empty or all files were excluded." >&2
    exit 1
  fi
  SCORE=$(percent "$COVERED" "$TOTAL")
  echo "Covered $COVERED of $TOTAL lines"
fi

echo "Coverage score: ${SCORE}%"

# Expose the score so each engine can surface it natively (job summary,
# MR widget, build description).
mkdir -p ci-artifacts
printf '%s' "$SCORE" > ci-artifacts/coverage-score.txt

if awk -v s="$SCORE" -v m="$MIN_COVERAGE" 'BEGIN { exit !(s < m) }'; then
  echo "Coverage ${SCORE}% is below threshold ${MIN_COVERAGE}%!" >&2
  exit 1
fi

echo "Coverage check passed: ${SCORE}% >= ${MIN_COVERAGE}%"
