#!/usr/bin/env bash
# Generated by zero_touch — do not edit by hand.
# Enforces numeric structural metrics on Dart code that Dart's analyzer cannot
# express, plus readability heuristics. Thresholds arrive via environment
# variables (set by every generated pipeline and by fastlane/.env locally);
# the defaults below are the generator presets and act only as a safety net.

set -euo pipefail

# Resolve each knob with explicit-environment precedence: a value already in
# the caller's environment (CI pipeline exports, local one-off overrides) wins
# over ci/.env (the generator's local defaults), which wins over the presets
# below. .env is never sourced just to clobber a caller-provided value.
resolve_knob() {
  local name="$1" default="$2" val
  val="${!name:-}"
  [ -n "$val" ] && { export "$name=$val"; return; }
  if [ -f .env ] && [ "$name" != "CI" ]; then
    val=$(sed -nE "s/^${name}=//p" .env | tail -1)
  fi
  [ -n "$val" ] || val="$default"
  export "$name=$val"
}

resolve_knob CI false
resolve_knob MAX_FUNCTION_LINES 60
resolve_knob MAX_FILE_LINES 600
resolve_knob MAX_PARAMETERS 6
resolve_knob MAX_NESTING_DEPTH 4
resolve_knob MAX_LINE_LENGTH 140
resolve_knob LINT_ENFORCE true
resolve_knob LINT_EXCLUDE ""

REPORT_DIR="ci-artifacts/lint"
REPORT="$REPORT_DIR/metrics.txt"
mkdir -p "$REPORT_DIR"
: > "$REPORT"

rule_off() {
  local id="$1" item
  for item in $LINT_EXCLUDE; do
    [ "$item" = "$id" ] && return 0
  done
  return 1
}

# mapfile may not exist on macOS bash 3.x, so use a compatible read loop.
FILES=()
while IFS= read -r f; do
  FILES+=("$f")
done < <(find lib test -name '*.dart' -type f 2>/dev/null \
  | grep -Ev '\.(g|freezed|pb|mocks)\.dart$' | sort || true)

if [ "${#FILES[@]}" -eq 0 ]; then
  echo "No Dart files found under lib/ or test/ — nothing to check."
  exit 0
fi

# --- numeric metric checks (one awk pass per file) -----------------------
# Function detection is intentionally heuristic (brace/paren balance, not a
# Dart AST): a line whose cleaned end is ') [async] {' and that is not an
# assignment or control keyword starts a function. Violations name the exact
# line so they are trivially auditable.
for file in "${FILES[@]}"; do
  awk -v file="$file" \
      -v max_fn="$MAX_FUNCTION_LINES" \
      -v max_file="$MAX_FILE_LINES" \
      -v max_nest="$MAX_NESTING_DEPTH" \
      -v max_line="$MAX_LINE_LENGTH" '
  function is_func_start(s,   t) {
    t = s
    sub(/^[ \t]+/, "", t)
    if (t ~ /^(if|for|while|switch|catch|else|do|return|with|try|finally)[ \t]*\(/) return 0
    if (t ~ /=/) return 0
    if (t !~ /\([^)]*\)/) return 0
    if (t !~ /[)}][ \t]*(async[ \t]*)?\{[ \t]*$/) return 0
    return 1
  }
  {
    line = $0
    if (line ~ /^[ \t]*$/ || line ~ /^[ \t]*(\/\/|\*)/) next
    clean = line
    gsub(/\/\/.*/, "", clean)
    start = depth
    opens = gsub(/\{/, "&", clean)
    closes = gsub(/\}/, "&", clean)

    if (active && start <= fn_start) {
      if (fn_len > max_fn) printf "%s:%d: function body is %d lines (max %d)\n", file, fn_ln, fn_len, max_fn
      active = 0
    }
    if (!active) {
      if (is_func_start(clean)) {
        active = 1
        fn_start = start
        fn_len = 0
        fn_ln = NR
      }
    } else if (start > fn_start) {
      fn_len++
    }

    depth = start + opens - closes
    if (depth > max_nest && depth > max_seen) {
      max_seen = depth
      max_seen_line = NR
    }
    if (length(clean) > max_line && clean !~ /https?:/) {
      printf "%s:%d: line length %d (max %d)\n", file, NR, length(clean), max_line
    }
    file_count++
  }
  END {
    if (active && fn_len > max_fn) printf "%s:%d: function body is %d lines (max %d)\n", file, fn_ln, fn_len, max_fn
    if (file_count > max_file) printf "%s: file has %d source lines (max %d)\n", file, file_count, max_file
    if (max_seen > max_nest) printf "%s:%d: nesting depth %d exceeds max %d\n", file, max_seen_line, max_seen, max_nest
  }
  ' "$file" >> "$REPORT" || true
done

# --- readability heuristics ----------------------------------------------
if ! rule_off no_magic_numbers; then
  for file in "${FILES[@]}"; do
    grep -nE '[^0-9a-zA-Z_.]([0-9]{1,2})(\.[0-9]+)?[^0-9a-zA-Z_.]' "$file" 2>/dev/null | \
      grep -viE '^[0-9]+:[[:space:]]*(static[[:space:]]+)?(import |part |export |const )' | \
      grep -viE '0x|Duration|fontSize|textScale|spacing|padding|margin|\bversion\b|\.0[0-9]' | \
      while IFS=: read -r ln rest; do
        printf '%s:%s: magic number literal\n' "$file" "$ln" >> "$REPORT"
      done || true
  done
fi

if ! rule_off comment_quality; then
  for file in "${FILES[@]}"; do
    grep -nE '^\s*//[^/].*(;|\{|\}| if \(| for \(| while \(| return )' "$file" 2>/dev/null | \
      while IFS=: read -r ln rest; do
        printf '%s:%s: commented-out code block\n' "$file" "$ln" >> "$REPORT"
      done || true
  done
fi

if ! rule_off boolean_name; then
  for file in "${FILES[@]}"; do
    grep -noE '\b(is|has|can|should|will)(Not|No)[A-Z][A-Za-z0-9_]*' "$file" 2>/dev/null | \
      while IFS=: read -r ln rest; do
        printf '%s:%s:%s: negated boolean name (prefer a positive name)\n' "$file" "$ln" "$rest" >> "$REPORT"
      done || true
  done
fi

if ! rule_off line_endings; then
  for file in "${FILES[@]}"; do
    if [ -s "$file" ] && [ "$(tail -c 1 "$file" | wc -l)" -eq 0 ]; then
      printf '%s: missing final newline (eol_at_end_of_file)\n' "$file" >> "$REPORT"
    fi
  done
fi

COUNT=$(wc -l < "$REPORT" | tr -d ' ')
printf 'ci/metrics.sh: %d violation(s) reported under %s\n' "$COUNT" "$REPORT_DIR"

if [ "$COUNT" -gt 0 ] && [ "$LINT_ENFORCE" = "true" ]; then
  echo "ci/metrics.sh: ${COUNT} structural/readability violation(s) found" >&2
  exit 3
fi
