#!/usr/bin/env bash
# Generated by zero_touch — do not edit by hand.
# Usage: notify_teams.sh <success|failure> "<stage name>" ["message"]
set -euo pipefail

WEBHOOK_URL="${TEAMS_WEBHOOK_URL:-}"
if [ -z "$WEBHOOK_URL" ]; then
  echo "TEAMS_WEBHOOK_URL not set — skipping Teams notification" >&2
  exit 0
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "jq not found — skipping Teams notification" >&2
  exit 0
fi

STATUS="${1:?Usage: notify_teams.sh <success|failure> <stage> [message]}"
STAGE="${2:?Usage: notify_teams.sh <success|failure> <stage> [message]}"
MESSAGE="${3:-}"

PROJECT="${PROJECT_NAME:-project}"
REF="${CI_REF:-${GITHUB_REF_NAME:-${CI_COMMIT_REF_NAME:-${BITBUCKET_BRANCH:-${BITBUCKET_TAG:-unknown ref}}}}}"

TITLE="$PROJECT — $STAGE $STATUS"
BODY="${MESSAGE:-$STAGE $STATUS on $REF}"

# Built via jq -n rather than string interpolation so a branch/tag name or
# message containing quotes can't produce invalid JSON.
PAYLOAD=$(jq -n --arg title "$TITLE" --arg body "$BODY" '{
  type: "message",
  attachments: [{
    contentType: "application/vnd.microsoft.card.adaptive",
    content: {
      "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
      type: "AdaptiveCard",
      version: "1.4",
      body: [
        {type: "TextBlock", text: $title, weight: "Bolder", size: "Medium"},
        {type: "TextBlock", text: $body, wrap: true}
      ]
    }
  }]
}')

# A broken/unreachable webhook must never fail the build.
curl -sf -X POST -H "Content-Type: application/json" -d "$PAYLOAD" "$WEBHOOK_URL" \
  || echo "⚠ Teams notification failed to send" >&2
