#!/usr/bin/env bash
# Generated by zero_touch — do not edit by hand.
# Installs the toolchain required to run the fastlane lanes.

set -euo pipefail

PROJECT_TYPE="${PROJECT_TYPE:?PROJECT_TYPE must be set}"

echo "Setting up tools for project type: $PROJECT_TYPE"

os_name="$(uname -s)"

install_pkg() {
  # Only macOS runners have Homebrew. Linux images used by GitLab and
  # Bitbucket ship the toolchain in the container, so a missing package is a
  # hard error there rather than something to silently skip.
  local pkg="$1"
  if [ "$os_name" = "Darwin" ] && command -v brew &>/dev/null; then
    brew list "$pkg" &>/dev/null || brew install "$pkg"
  else
    echo "Expected '$pkg' to be provided by the CI image on $os_name"
  fi
}

case "$PROJECT_TYPE" in
  ios)
    command -v swiftlint &>/dev/null || install_pkg swiftlint
    xcodebuild -version
    ;;
  android)
    command -v gradle &>/dev/null || install_pkg gradle
    gradle --version
    ;;
  flutter)
    flutter --version
    flutter pub get
    ;;
  *)
    echo "Unsupported project type: $PROJECT_TYPE" >&2
    exit 1
    ;;
esac

# Ruby side: resolve fastlane through bundler only. Installing fastlane
# globally as well would leave two different versions on the runner, and the
# bare `fastlane` binary would win over the locked one.
if ! command -v bundle &>/dev/null; then
  gem install bundler --no-document -q
fi

bundle config set --local path vendor/bundle
bundle install --jobs 4 --retry 3 --quiet
bundle exec fastlane --version

echo "Setup complete"
