#!/usr/bin/env bash
# Generated by zero_touch — do not edit by hand.
# Local-only code quality check against a SonarQube server.
# Not wired into any generated CI pipeline — run manually:
#   SONAR_TOKEN=<token> bash ci/sonarqube.sh

set -euo pipefail

PROJECT_TYPE="${PROJECT_TYPE:?PROJECT_TYPE must be set}"
SONAR_HOST_URL="${SONAR_HOST_URL:-http://localhost:9000}"
SONAR_PROJECT_KEY="${SONAR_PROJECT_KEY:-$PROJECT_TYPE}"
SONAR_TOKEN="${SONAR_TOKEN:?SONAR_TOKEN must be set — generate one in SonarQube under My Account > Security}"

echo "Running local SonarQube check for $SONAR_PROJECT_KEY against $SONAR_HOST_URL"

# --- ensure sonar-scanner is available ------------------------------------
if ! command -v sonar-scanner &>/dev/null; then
  read -p "sonar-scanner not found. Install it via Homebrew now? [y/N] " REPLY
  if [[ "$REPLY" =~ ^[Yy]$ ]]; then
    brew install sonar-scanner
  else
    echo "sonar-scanner is required. Install manually: https://docs.sonarsource.com/sonarqube/latest/analyzing-source-code/scanners/sonarscanner/" >&2
    exit 1
  fi
fi

# --- ensure a SonarQube server is reachable -------------------------------
server_up() {
  curl -sf "$SONAR_HOST_URL/api/system/status" 2>/dev/null | grep -q '"status":"UP"'
}

if ! server_up; then
  case "$SONAR_HOST_URL" in
    *localhost*|*127.0.0.1*)
      read -p "SonarQube server not reachable at $SONAR_HOST_URL. Install and start it locally via Homebrew now? [y/N] " REPLY
      if [[ "$REPLY" =~ ^[Yy]$ ]]; then
        brew install sonarqube
        brew services start sonarqube
        echo "Waiting for SonarQube to start (this can take a minute)..."
        UP=false
        for _ in $(seq 1 30); do
          if server_up; then
            UP=true
            break
          fi
          sleep 5
        done
        if [ "$UP" = false ]; then
          echo "SonarQube did not come up at $SONAR_HOST_URL within the timeout." >&2
          exit 1
        fi
      else
        echo "A running SonarQube server is required at $SONAR_HOST_URL." >&2
        exit 1
      fi
      ;;
    *)
      echo "SonarQube server not reachable at $SONAR_HOST_URL. Start/point at a running server and retry." >&2
      exit 1
      ;;
  esac
fi

# --- resolve project-type-specific scanner properties ---------------------
SONAR_ARGS=(-Dsonar.host.url="$SONAR_HOST_URL" -Dsonar.token="$SONAR_TOKEN" -Dsonar.projectKey="$SONAR_PROJECT_KEY")

case "$PROJECT_TYPE" in
  flutter)
    SONAR_ARGS+=(-Dsonar.sources=lib -Dsonar.exclusions="**/*.g.dart,**/*.freezed.dart,**/*.pb.dart")
    [ -f coverage/lcov.info ] && SONAR_ARGS+=(-Dsonar.dart.coverage.reportPath=coverage/lcov.info)
    ;;
  android)
    SONAR_ARGS+=(-Dsonar.sources=app/src/main -Dsonar.java.binaries=app/build)
    JACOCO=$(find build app/build -name "jacocoTestReport.xml" -type f 2>/dev/null | head -n 1 || true)
    [ -n "$JACOCO" ] && SONAR_ARGS+=(-Dsonar.coverage.jacoco.xmlReportPaths="$JACOCO")
    ;;
  ios)
    SONAR_ARGS+=(-Dsonar.sources=Sources)
    ;;
  *)
    echo "Unsupported project type: $PROJECT_TYPE" >&2
    exit 1
    ;;
esac

echo "Running sonar-scanner..."
sonar-scanner "${SONAR_ARGS[@]}"

# --- wait for background analysis, then fetch the result ------------------
REPORT_TASK=".scannerwork/report-task.txt"
if [ ! -f "$REPORT_TASK" ]; then
  echo "Scanner did not produce $REPORT_TASK — cannot look up analysis result." >&2
  exit 1
fi

CE_TASK_URL=$(sed -nE 's/^ceTaskUrl=//p' "$REPORT_TASK")

echo "Waiting for SonarQube analysis to complete..."
ANALYSIS_ID=""
for _ in $(seq 1 30); do
  TASK_JSON=$(curl -sf -u "$SONAR_TOKEN:" "$CE_TASK_URL")
  STATUS=$(printf '%s' "$TASK_JSON" | jq -r '.task.status')
  if [ "$STATUS" = "SUCCESS" ]; then
    ANALYSIS_ID=$(printf '%s' "$TASK_JSON" | jq -r '.task.analysisId')
    break
  elif [ "$STATUS" = "FAILED" ] || [ "$STATUS" = "CANCELED" ]; then
    echo "SonarQube background analysis $STATUS." >&2
    exit 1
  fi
  sleep 2
done

if [ -z "$ANALYSIS_ID" ]; then
  echo "Timed out waiting for SonarQube analysis to complete." >&2
  exit 1
fi

# --- write report, in the same style as ci/metrics.sh's metrics.txt -------
REPORT_DIR="ci-artifacts/sonarqube"
REPORT="$REPORT_DIR/report.txt"
mkdir -p "$REPORT_DIR"

GATE_JSON=$(curl -sf -u "$SONAR_TOKEN:" "$SONAR_HOST_URL/api/qualitygates/project_status?analysisId=$ANALYSIS_ID")
GATE_STATUS=$(printf '%s' "$GATE_JSON" | jq -r '.projectStatus.status')
DASHBOARD_URL="$SONAR_HOST_URL/dashboard?id=$SONAR_PROJECT_KEY"

{
  echo "Quality Gate: $GATE_STATUS"
  echo "Dashboard: $DASHBOARD_URL"
  echo ""
} > "$REPORT"

curl -sf -u "$SONAR_TOKEN:" "$SONAR_HOST_URL/api/issues/search?componentKeys=$SONAR_PROJECT_KEY&resolved=false&ps=500" \
  | jq -r '.issues[] | "\(.component | sub("^[^:]+:"; "")):\(.line // 0): [\(.severity)] \(.rule) — \(.message)"' \
  >> "$REPORT"

COUNT=$(( $(wc -l < "$REPORT" | tr -d ' ') - 3 ))
[ "$COUNT" -lt 0 ] && COUNT=0
printf 'ci/sonarqube.sh: %d issue(s) reported under %s\n' "$COUNT" "$REPORT_DIR"
echo "Full dashboard: $DASHBOARD_URL"

if [ "$GATE_STATUS" = "ERROR" ]; then
  echo "SonarQube quality gate failed." >&2
  exit 1
fi

echo "SonarQube quality gate passed."
